const AppStrings = {
  appName: "ГРАВИТИНО АСУР",
  signInDescription: "Войдите в свой аккаунт",
  signUpDescription: "Зарегистрироваться",
  rememberSignIn: "Запомнить меня",
  noAccount: "У вас нет учетной записи?",
  register: "Зарегистрироваться",
  hasAccount: "У вас уже есть аккаунт?",
  signIn: "Войти",
  next: "Далее",
  differentPasswords: "Пароли не совпадают!",
  workType: "Описание вида работы",
  workTypeDescription: "Описание задания",
  branch: "Филиал",
  category: "Категория",
  priority: "Приоритет",
  comment: "Комментарий к задаче",
  shortDateFormat: "DD.MM.YYYY",
  longDateFormat: "DD/MM/YYYY HH:mm",
  search: "Искать...",
  today: "Сегодня",
  tomorrow: "Завтра",
  yesterday: "Вчера",
  week: "Неделя",
  unread: "Непрочитанные",
  read: "Прочитанные",
  setFilter: "Подобрать фильтр",
  taskType: "Тип задания",
  status: "Статус",
  sortTasks: "Сортировать задачи",
  apply: "Применить",
  emptyOrderList: "Пока нет активных задач",
  attachFilesDescription: "Прикрепить изображения, максимум 10",
  press: "Нажмите",
  toMakePhoto: "чтобы сделать Фото",
  toUpload: "чтобы Загрузить",
  tooManyImages: "Можно выбрать только 10 изображений",
  imageDeleted: "Изображение удалено!",
  defaultError: "Ошибка!",
};
export default AppStrings;
