const AppStrings = {
    appName: 'ГРАВИТИНО АСУР',
    gravitino: 'Гравитино',
    signInDescription: 'Войдите в свой аккаунт',
    signUpDescription: 'Зарегистрироваться',
    rememberSignIn: 'Запомнить меня',
    noAccount: 'У вас нет учетной записи?',
    register: 'Зарегистрироваться',
    hasAccount: 'У вас уже есть аккаунт?',
    signIn: 'Войти',
    next: 'Далее',
    differentPasswords: 'Пароли не совпадают!',
    workType: 'Описание вида работы',
    workTypeDescription: 'Описание задания',
    category: 'Категория',
    priority: 'Приоритет',
    comment: 'Комментарий к задаче',
    shortDateFormat: 'DD.MM.YYYY',
    longDateFormat: 'DD/MM/YYYY HH:mm',
    search: 'Поиск по названию...',
    today: 'Сегодня',
    tomorrow: 'Завтра',
    yesterday: 'Вчера',
    week: 'Неделя',
    unread: 'Непрочитанные',
    read: 'Прочитанные',
    setFilter: 'Подобрать фильтр',
    taskType: 'Тип задания',
    status: 'Статус',
    selectValue: 'Выберите значение',
    sortTasks: 'Сортировать задачи',
    apply: 'Применить',
    emptyOrderList: 'Пока нет активных задач',
    attachFilesDescription: 'Прикрепить изображения, максимум 10',
    press: 'Нажмите',
    toMakePhoto: 'чтобы сделать Фото',
    toUpload: 'чтобы Загрузить',
    tooManyImages: 'Можно выбрать только 10 изображений',
    imageDeleted: 'Изображение удалено!',
    defaultError: 'Ошибка!',
    orderCreated: 'Создана',
    orderAssigned: 'Назначена',
    orderInProgress: 'В работе',
    orderOnVerification: 'На проверке',
    orderClosed: 'Закрыта',
    orderCancelled: 'Отменена',
    orderDeadlineClosed: 'Закрыта с нарушением дедлайна',
    orderNeedWork: 'Необходима доработка',
    orderNotAssigned: 'Не назначена',
    name: 'Название',
    description: 'Описание',
    branch: 'Филиал',
    checkpoint: 'Пункт пропуска',
    facility: 'Объект обслуживания',
    closeOrder: 'Закрыть задачу',
    madeIn: 'Сделано в ',
    cameraAccessError:
        'Доступ к камере заблокирован. Измените разрешение в настройках.',
    ordersInWork: 'Задачи в работе',
    closedOrders: 'Завершенные задачи',
    loading: 'Загрузка...',
}
export default AppStrings
